# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:ios)

#platform :ios do
 # desc "Description of what the lane does"
  lane :beta do
increment_build_number
gym(scheme: "TestProject", 
  workspace: "TestProject.xcworkspace",
  configuration: "Ad Hoc Distribution")
firebase_app_distribution(
	firebase_cli_token: "1//09JHpYQ3jrnVsCgYIARAAGAkSNwF-L9IrIMsMrBLwgbW9DA0FRFymgmBrPWMaz8dPbkoUx2frbD9Msr-VAN6Ozp2gd1Q9ASw1HpM",
            testers: "ilyatkachev6@gmail.com",
            release_notes: "Lots of amazing new features to test out!"
        )
 
	

end


